# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  university.40q.agency:
    site_hosts:
      - canonical: university.40q.test
        redirects:
          - www.university.40q.test
    local_path: ..
    public_path: public
    upload_path: content/uploads
    admin_email: admin@university.40q.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
    xmlrpc:
      enabled: false
