# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  university.40q.agency:
    site_hosts:
      - canonical: university.40q.agency
        redirects:
          - www.university.40q.agency
    local_path: ..
    public_path: public
    upload_path: content/uploads
    repo: git@github.com:40Q/40q-university.git
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
    xmlrpc:
      enabled: false
